spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lista_zadan?serverTimezone=UTC
    username: root
    password: *
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        fromat_sql: true

logging.level.org.hibernate.type: trace
