spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lista_zadan?serverTimezone=UTC
    username: root
    password: *
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: embedded
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        fromat_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

logging.level.org.hibernate.type: trace
